"""fixing submissin

Revision ID: 14933e072b35
Revises: 1e1527203992
Create Date: 2024-02-08 20:48:28.346892

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14933e072b35"
down_revision: Union[str, None] = "1e1527203992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column("submission_amount", sa.Integer(), nullable=False),
    )
    op.drop_column("addresses", "submissin_amount")
    op.add_column(
        "clients",
        sa.Column("submission_amount", sa.Integer(), nullable=False),
    )
    op.drop_column("clients", "submissin_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "submissin_amount",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("clients", "submission_amount")
    op.add_column(
        "addresses",
        sa.Column(
            "submissin_amount",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("addresses", "submission_amount")
    # ### end Alembic commands ###
