"""fixing basemodel

Revision ID: 1e1527203992
Revises: 544e89409846
Create Date: 2024-02-08 20:46:03.353599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e1527203992"
down_revision: Union[str, None] = "544e89409846"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "addresses",
        sa.Column("submissin_amount", sa.Integer(), nullable=False),
    )
    op.drop_column("addresses", "count")
    op.add_column(
        "clients",
        sa.Column("submissin_amount", sa.Integer(), nullable=False),
    )
    op.drop_column("clients", "count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("clients", "submissin_amount")
    op.add_column(
        "addresses",
        sa.Column(
            "count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("addresses", "submissin_amount")
    # ### end Alembic commands ###
