"""fixing addresses table

Revision ID: 449cb372a695
Revises: fea41b65bbb9
Create Date: 2024-02-08 20:32:27.222794

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "449cb372a695"
down_revision: Union[str, None] = "fea41b65bbb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
