"""changing count field

Revision ID: 50a3f4a431f7
Revises: 311a2e572b58
Create Date: 2024-02-07 22:35:24.872310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50a3f4a431f7"
down_revision: Union[str, None] = "311a2e572b58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("is_spam", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "is_spam")
    # ### end Alembic commands ###
