"""Added email field to client

Revision ID: 668b9069ab86
Revises: 14933e072b35
Create Date: 2024-02-12 01:47:16.774837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "668b9069ab86"
down_revision: Union[str, None] = "14933e072b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("email", sa.String(), nullable=True))
    op.alter_column(
        "clients", "phone", existing_type=sa.BIGINT(), nullable=True
    )
    op.create_index(
        op.f("ix_clients_email"), "clients", ["email"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.alter_column(
        "clients", "phone", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("clients", "email")
    # ### end Alembic commands ###
