"""changing count field

Revision ID: faff79844b87
Revises: 50a3f4a431f7
Create Date: 2024-02-07 22:36:31.668395

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "faff79844b87"
down_revision: Union[str, None] = "50a3f4a431f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
