"""adding addresses table

Revision ID: fea41b65bbb9
Revises: faff79844b87
Create Date: 2024-02-08 20:07:35.495490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fea41b65bbb9"
down_revision: Union[str, None] = "faff79844b87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("is_spam", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_addresses_ip"), "addresses", ["ip"], unique=True
    )
    op.create_table(
        "join_client_address",
        sa.Column("client_id", sa.String(), nullable=True),
        sa.Column("address_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("join_client_address")
    op.drop_index(op.f("ix_addresses_ip"), table_name="addresses")
    op.drop_table("addresses")
    # ### end Alembic commands ###
